### ISSUE TITLE
Update the CSS [Hacktoberfest]

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/WebDevHackathon#2]
Design the complete Web_Page in a new fancy Look

**Comment by Harsh-00** [comment]
Hello, I'm interested in working on this issue. Could you please assign it to me?

**Comment by narasimha-1511** [comment]
Go on @Harsh-00 
Thank You For showing Intrest

**Comment by TusharRastogi04** [comment]
hi @narasimha-1511  can you please assign this issue to me as it looks a goodfit for my field

**Comment by Harsh-00** [comment]
I appreciate your feedback and value your input. If you find anything unsatisfactory or if there are any issues, please feel free to let me know. @narasimha-1511

**Comment by Blink29** [comment]
Hi can you please assign me the issue

**Comment by narasimha-1511** [comment]
Hey Thank You!! @Harsh-00

**Comment by Harsh-00** [comment]
Could you please consider adding the 'Hacktoberfest-accepted' label to this pull request as it assists in tracking contributions for Hacktoberfest.
