### ISSUE TITLE
Improve the color coding of the Website ..

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/WebDevHackathon#4]

**Comment by shikharg1110** [comment]
Can you assign me this task. I will improve the color of the website

**Comment by narasimha-1511** [comment]
go on @shikharg1110 :confetti_ball:

**Comment by shreyashaw05** [comment]
I would lke to work on this....
Can i still work on it?

**Comment by shikharg1110** [comment]
Could you tell me which color combination you would like me to code
Dark color combination OR Light color combination

![B](https://github.com/narasimha-1511/WebDevHackathon/assets/114243045/cc454ced-68e6-422d-9fe3-d9f99e78c40c)
![C](https://github.com/narasimha-1511/WebDevHackathon/assets/114243045/e477b259-8cfc-48ee-9091-4a5ebee93395)
![A](https://github.com/narasimha-1511/WebDevHackathon/assets/114243045/25083afc-33f6-4076-bcd3-5c15820bd6df)

**Comment by narasimha-1511** [comment]
Dark Color 

I would Prefer to add a switch toogle button
with dark and light mode ..

**Comment by narasimha-1511** [comment]
@shreya17105  i gave the assingee according to the order you can search for the other issues in the repositories
